Improve error message for early Python 3.X.
Before:

        lambda: (yield from 0)  # Python >= 3.4 is required
                          ^
    SyntaxError: invalid syntax

After:

    RuntimeError: Python >= 3.4 is required